export const ADD = 'ADD'
export const DEL = 'DEL'
export const ADD_LIST = 'ADD_LIST'
export const DEL_LIST = 'DEL_LIST'
export const ADD_BUYLIST = 'ADD_BUYLIST'
export const ADD_CAR_COUNT = 'ADD_CAR_COUNT'